<?php

const AWS_ACCESS_KEY = 'YOUR_ACCESS_KEY';
const AWS_SECRET_KEY = 'YOUR_SECRET_KEY';
const AWS_SES_VERSION = 'YOUR_SES_VERSION';
const AWS_REGION = 'YOUR_SES_REGION';
const CHAR_SET = 'YOUR_SES_CHARSET';
